title      : Rare计划官网
lang       : zh
description: 打造最棒的手表应用
copyright  : © 2023 - 2023 genouka All Rights Reserved
extra      : 本网站属于非盈利性质网站，不进行任何商业经营活动。

nav:
 - name: 应用
   link: /
 - name: 联系
   link: /lianxi/
 - name: 友链
   link: /link/

links:
 - name: AIDE高级设置版
   link: https://www.aidepro.top/